import os
import sqlite3
import pandas as pd
import numpy as np
from typing import Dict, Any, List, Tuple
from utils.llm_client import llm_client
from agents.sql_agent import get_db_schema, clean_sql, contains_unsafe_sql
from dotenv import load_dotenv

load_dotenv()

DB_PATH = os.getenv("DB_PATH", "db.sqlite")

def run_db_query(sql: str) -> pd.DataFrame:
    """
    Executes raw SQL query and returns a pandas DataFrame.
    """
    conn = sqlite3.connect(DB_PATH)
    try:
        df = pd.read_sql_query(sql, conn)
        return df
    finally:
        conn.close()

def generate_forecast_query(query: str) -> str:
    """
    Asks the LLM to generate a SQLite query yielding columns 'ds' and 'y' for forecasting.
    """
    schema = get_db_schema()
    system_prompt = f"""You are a SQLite expert.
Generate a SQLite query to fetch historical time series data for forecasting based on the user's question.
The query MUST return exactly two columns:
- 'ds': date formatted as 'YYYY-MM-DD'
- 'y': the numeric value to forecast (e.g. sum of revenue, sum of units, etc. based on the question)

Database Schema:
{schema}

Rules:
- Return ONLY the SQL query. Do not write anything else. Do not wrap in markdown blocks.
- Group the data by date so there is only one row per date.
- SELECT statements only.
"""
    try:
        raw_sql = llm_client.query(
            prompt=f"Question: {query}",
            system_prompt=system_prompt
        )
        sql = clean_sql(raw_sql)
        
        # Check safety
        if contains_unsafe_sql(sql):
            raise ValueError("Unsafe SQL generated by forecast helper.")
            
        return sql
    except Exception as e:
        print(f"Error generating forecast SQL: {e}. Using fallback query.")
        # Fallback: total revenue by date
        return "SELECT date as ds, SUM(revenue) as y FROM sales GROUP BY date ORDER BY date"

def run_forecast_model(df: pd.DataFrame, periods: int = 30) -> Tuple[pd.DataFrame, str]:
    """
    Attempts to forecast using Prophet. If Prophet is missing or fails, falls back to statsmodels ARIMA.
    Returns:
        - DataFrame containing ds, yhat, yhat_lower, yhat_upper
        - String indicating which model was used ("Prophet" or "ARIMA")
    """
    # Standardize data types
    df = df.copy()
    df['ds'] = pd.to_datetime(df['ds'])
    df['y'] = pd.to_numeric(df['y'])
    df = df.sort_values('ds').reset_index(drop=True)
    
    # Ensure regular daily frequency
    df = df.set_index('ds')
    df = df.resample('D').sum().fillna(0).reset_index()
    
    # Try Prophet first
    try:
        from prophet import Prophet
        import logging
        # Mute prophet logs
        logging.getLogger('prophet').setLevel(logging.ERROR)
        
        # Prophet expects columns 'ds' and 'y'
        m = Prophet(daily_seasonality=False, weekly_seasonality=True, yearly_seasonality=False)
        m.fit(df)
        
        future = m.make_future_dataframe(periods=periods)
        forecast = m.predict(future)
        
        # Get only the forecasted rows
        forecast_part = forecast.tail(periods)[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]
        # Convert ds back to string format
        forecast_part['ds'] = forecast_part['ds'].dt.strftime('%Y-%m-%d')
        
        return forecast_part, "Prophet"
        
    except (ImportError, Exception) as prophet_err:
        print(f"Prophet forecast unavailable or failed ({prophet_err}). Falling back to ARIMA...")
        
        try:
            from statsmodels.tsa.arima.model import ARIMA
            
            # Format time series index
            df_ts = df.set_index('ds')
            
            # Fit simple ARIMA model (order p=1, d=1, q=1 is robust for trended data)
            model = ARIMA(df_ts['y'], order=(1, 1, 1))
            model_fit = model.fit()
            
            # Forecast next periods
            forecast_res = model_fit.get_forecast(steps=periods)
            forecast_mean = forecast_res.predicted_mean
            forecast_ci = forecast_res.conf_int()
            
            # Construct dates for the future
            last_date = df_ts.index[-1]
            future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=periods, freq='D')
            
            forecast_part = pd.DataFrame({
                'ds': future_dates.strftime('%Y-%m-%d'),
                'yhat': forecast_mean.values,
                'yhat_lower': forecast_ci.iloc[:, 0].values,
                'yhat_upper': forecast_ci.iloc[:, 1].values
            })
            
            return forecast_part, "ARIMA"
        except Exception as arima_err:
            print(f"ARIMA forecast also failed: {arima_err}")
            # Construct a basic linear extrapolation as absolute fallback
            last_date = df['ds'].iloc[-1]
            last_val = df['y'].iloc[-1]
            mean_val = df['y'].mean()
            
            future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=periods, freq='D')
            yhat = [last_val + (last_val - mean_val) * (i / periods) * 0.1 for i in range(1, periods + 1)]
            
            forecast_part = pd.DataFrame({
                'ds': future_dates.strftime('%Y-%m-%d'),
                'yhat': yhat,
                'yhat_lower': [y * 0.8 for y in yhat],
                'yhat_upper': [y * 1.2 for y in yhat]
            })
            
            return forecast_part, "Linear Extrapolation (Fallback)"

def run_forecast_agent(query: str) -> Dict[str, Any]:
    """
    Forecasting Agent Flow: Generate query -> Extract History ->
    Model Fit & Prediction -> Explain Forecast -> Return results.
    """
    try:
        sql = generate_forecast_query(query)
        df_history = run_db_query(sql)
        
        if df_history.empty or len(df_history) < 5:
            return {
                "query": query,
                "historical_data": [],
                "forecast_data": [],
                "model_used": "None",
                "explanation": "Not enough historical data in database to produce a forecast."
            }
            
        # Ensure correct column names
        if 'ds' not in df_history.columns or 'y' not in df_history.columns:
            # Try to map columns if not returned as ds and y
            if len(df_history.columns) >= 2:
                df_history.columns = ['ds', 'y'] + list(df_history.columns[2:])
            else:
                raise ValueError("DB Query did not return sufficient columns for forecasting.")
                
        # Run forecasting model
        forecast_df, model_used = run_forecast_model(df_history, periods=30)
        
        # Prepare data for explanation prompt
        forecast_summary_list = []
        for _, row in forecast_df.iterrows():
            forecast_summary_list.append(
                f"Date: {row['ds']}, Expected Value: {row['yhat']:.2f} (Confidence Interval: [{row['yhat_lower']:.2f}, {row['yhat_upper']:.2f}])"
            )
        forecast_str = "\n".join(forecast_summary_list[:5]) + "\n... [truncated] ...\n" + "\n".join(forecast_summary_list[-5:])
        
        # Explain forecast
        explain_prompt = f"""Given this forecast data:
{forecast_str}

Explain the trend in plain language for a business audience.
Mention confidence level and any notable seasonality.
Original question: {query}
"""
        explanation = llm_client.query(
            prompt=explain_prompt,
            system_prompt="You are a senior business analyst explaining forecasts to executives."
        )
        
        # Convert history df to list of dicts for serialization
        # Convert ds in history to string format
        df_history['ds'] = pd.to_datetime(df_history['ds']).dt.strftime('%Y-%m-%d')
        historical_list = df_history[['ds', 'y']].to_dict(orient='records')
        forecast_list = forecast_df.to_dict(orient='records')
        
        return {
            "query": query,
            "historical_data": historical_list,
            "forecast_data": forecast_list,
            "model_used": model_used,
            "explanation": explanation
        }
        
    except Exception as e:
        print(f"Forecast Agent error: {e}")
        return {
            "query": query,
            "historical_data": [],
            "forecast_data": [],
            "model_used": "None",
            "explanation": f"Forecast Agent failed to run: {str(e)}"
        }

if __name__ == "__main__":
    # Test Forecast Agent
    print("Testing Forecast Agent...")
    # Mock some data if needed, or check
    if os.path.exists(DB_PATH):
        test_result = run_forecast_agent("Forecast total sales units for next 30 days")
        print("Model Used:", test_result["model_used"])
        print("Historical Count:", len(test_result["historical_data"]))
        print("Forecast Count:", len(test_result["forecast_data"]))
        print("Explanation:\n", test_result["explanation"])
    else:
        print("Run seed_db.py first to test forecast agent.")
